### ISSUE TITLE
repository 'https://github.com/holochain/where/' not found

### ISSUE THREAD

**Issue by bhaugen** [lightningrodlabs/where#31]
[nix-shell:~]$ git clone https://github.com/holochain/where && cd ./where
Cloning into 'where'...
Username for 'https://github.com': bhaugen
Password for 'https://bhaugen@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/holochain/where/' not found

**Comment by bhaugen** [comment]
Should 
https://github.com/holochain/where/
be replaced by 
https://github.com/lightningrodlabs/where/
?

Yes! That worked.

**Comment by zippy** [comment]
Yep. Where is an LRL project

**Comment by zippy** [comment]
Fixed
