### ISSUE TITLE
Issue installing using Holochain Launcher

### ISSUE THREAD

**Issue by bierlingm** [lightningrodlabs/where#4]
I'm on a MacBook Pro 15-inch 2017 with Monterey 12.0 Beta (21A5506j) installed. I've downloaded the Holochain Launcher v0.2.2 and downloaded the release files where.happ and ui.zip and attempted to install them using the launcher. When I do so I get the following error:

<img width="465" alt="Screen Shot 2021-09-16 at 12 30 38" src="https://user-images.githubusercontent.com/9335771/133596886-2fa94bf9-a578-4055-863e-b27a19f0a018.png">

**Comment by zippy** [comment]
Thanks @bierlingm!  Working on it.

**Comment by zippy** [comment]
Works now on latest launchers...
